#!/usr/bin/env python3
"""
Update artifact metadata JSON files with URLs after upload to GitHub Releases.

This script updates existing metadata files generated by build.yml with real
GitHub Release URLs after packages have been uploaded by upload-releases.yml.

Usage:
    python3 update_metadata_urls.py \
        --metadata-file catalog/node_exporter/rpm_amd64_el9.json \
        --url https://github.com/.../node_exporter-1.10.2-1.el9.x86_64.rpm
"""

import argparse
import json
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Update artifact metadata with GitHub Release URL"
    )
    parser.add_argument(
        "--metadata-file",
        required=True,
        help="Path to existing metadata JSON file",
    )
    parser.add_argument(
        "--url",
        required=True,
        help="GitHub Release download URL for the package",
    )

    args = parser.parse_args()

    metadata_path = Path(args.metadata_file)

    if not metadata_path.exists():
        print(f"Error: Metadata file not found: {metadata_path}", file=sys.stderr)
        sys.exit(1)

    # Load existing metadata
    with open(metadata_path) as f:
        metadata = json.load(f)

    # Validate format
    if metadata.get("format_version") != "3.0":
        print(
            f"Warning: Expected format_version 3.0, got {metadata.get('format_version')}"
        )

    # Update URL in package section
    if "package" in metadata:
        old_url = metadata["package"].get("url", "")
        metadata["package"]["url"] = args.url
        print(f"Updated URL: '{old_url}' → '{args.url}'")
    else:
        print("Error: No 'package' section found in metadata", file=sys.stderr)
        sys.exit(1)

    # Write updated metadata back to file
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"✓ Metadata updated: {metadata_path}")


if __name__ == "__main__":
    main()
